spring:
  backend:
    base-url: ${BACKEND_BASE_URL}

  batch:
    application:
      name: ${ZIPHAP_BATCH_APPLICATION_NAME}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_DATABASE_PORT}/${RDS_DATABASE_NAME}
    username: ${RDS_USER_NAME}
    password: ${RDS_USER_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  OAuth2:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      callback-url: ${GOOGLE_CLIENT_CALLBACK_URL}
      url: https://accounts.google.com/o/oauth2/v2/auth
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
      token: https://oauth2.googleapis.com/token
      user-info: https://www.googleapis.com/oauth2/v1/userinfo
    kakao:
      client-id: ${KAKAO_CLIENT_ID}
      redirect-uri: ${KAKAO_CLIENT_CALLBACK_URL}
      token: https://kauth.kakao.com/oauth/token
      user-info: https://kapi.kakao.com/v2/user/me
      page-uri: https://kauth.kakao.com/oauth/authorize
      logout-uri: https://kapi.kakao.com/v1/user/logout

  jwt:
    secret: ${JWT_SECRET}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE