spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  h2:
    console:
      enabled: true
      path: /h2-console
    datasource:
      url: jdbc:h2:tcp://localhost/~/ziphap
      driver-class-name: org.h2.Driver
      username: sa
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      properties.hibernate.hbm2ddl.auto: none
      showSql: true
      properties:
        hibernate:
        default_batch_fetch_size: 1000

  jwt:
    secret: JDKdldsjkdndsljJKDJLsdafldlJOkjd-jldkjadfsaOJUJNsdlsdjdsknslefipsjkewkw
  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      client-id: 767085427001-c220ums6k5ntb78vv7rma8ne46den43g.apps.googleusercontent.com
      client-secret: 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
      callback-url: http://localhost:8080/accounts/auth/google/callback
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
      token: https://oauth2.googleapis.com/token
      user-info: https://www.googleapis.com/oauth2/v1/userinfo
    kakao:
      client-id: 44a3c35e7086a6cea10ebddd03df7aa7
      token: https://kauth.kakao.com/oauth/token
      user-info: https://kapi.kakao.com/v2/user/me
      redirect-uri: http://localhost:8080/accounts/auth/kakao/callback
      page-uri: https://kauth.kakao.com/oauth/authorize
      logout-uri: https://kapi.kakao.com/v1/user/logout