spring:
  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      client-id: 767085427001-c220ums6k5ntb78vv7rma8ne46den43g.apps.googleusercontent.com
      client-secret: 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
      callback-url: http://localhost:8080/accounts/auth/google/callback
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile