spring:
  batch:
    application:
      name: ZIPHAP_BACKEND_BATCH

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ziphap
    username: root
    password: ksh03050621

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none

  OAuth2:
    google:
      client-id: 767085427001-c220ums6k5ntb78vv7rma8ne46den43g.apps.googleusercontent.com
      client-secret: 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
      callback-url: http://localhost:8080/accounts/auth/google/callback
      url: https://accounts.google.com/o/oauth2/v2/auth
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
      token: https://oauth2.googleapis.com/token
      user-info: https://www.googleapis.com/oauth2/v1/userinfo
    kakao:
      client-id: 44a3c35e7086a6cea10ebddd03df7aa7
      redirect-uri: http://localhost:8080/accounts/auth/kakao/callback
      token: https://kauth.kakao.com/oauth/token
      user-info: https://kapi.kakao.com/v2/user/me
      page-uri: https://kauth.kakao.com/oauth/authorize
      logout-uri: https://kapi.kakao.com/v1/user/logout

  jwt:
    secret: JDKdldsjkdndsljJKDJLsdafldlJOkjd-jldkjadfsaOJUJNsdlsdjdsknslefipsjkewkw

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE