name: house-work-backend-main-ci

on:
  push:
    branches:
      - main
      - feature/analysis
  workflow_dispatch:

env:
  JAVA_VERSION: 11
  DISTRIBUTION: temurin
  MYSQL_CHARACTER: utf8
  MYSQL_DATABASE: ziphap
  MYSQL_USER: root
  MYSQL_PASSWORD: ksh03050621

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}

      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: ${{ env.MYSQL_CHARACTER }}
          mysql database: ${{ env.MYSQL_DATABASE }}
          mysql user: ${{ env.MYSQL_USER }}
          mysql password: ${{ env.MYSQL_PASSWORD }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash