name: house-work-backend-main-to-beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notifier-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build Root Project
        run: ./gradlew build
        shell: bash

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDTHHmm
          utcOffset: "+09:00"

      - name: Generate Api package
        run: |
          mkdir -p deploy-notifier
          cp api/build/libs/api.jar deploy-notifier/notifier-production-ebextensions-1.jar
          cp Procfile deploy-notifier/Procfile
          cp -r .ebextensions deploy-notifier/.ebextensions
          cd deploy-notifier && zip -r notifier-production-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip .

      - name: Deploy Api to ElasticBeansTalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: notifier
          environment_name: notifier-prod
          version_label: notifier-production-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}
          region: ap-northeast-2
          deployment_package: deploy-notifier/notifier-production-${{steps.current-time.outputs.formattedTime}}-${{github.sha}}.zip